# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Services
    hasChildren: true
    weight: 20
  - name: Zero Point Myofascial Release
    parent: Services
    url: zero-point-myofascial-release/
    weight: 10
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
